version: '3.4'

services:
  scprime:
    container_name: portfolio3
    image: portfolio3:latest

    ports:
      - 5000:5000
    volumes:
      - data:/portfolio/data
    restart: unless-stopped
volumes:
  data:
