"""Table Variables

Revision ID: 8aa0e6178151
Revises: 62d9682c45db
Create Date: 2018-06-24 16:39:25.297213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa0e6178151'
down_revision = '62d9682c45db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variables',
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variables')
    # ### end Alembic commands ###
